//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesShopManagement.Model
{
    using ClothesShopManagement.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM:BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CTHDs = new HashSet<CTHD>();
            this.CTPNs = new HashSet<CTPN>();
        }
    
        public string MASP { get; set; }
        private string _TENSP;
        public string TENSP { get=> _TENSP; set { _TENSP = value; OnPropertyChanged(); } }
        public string DVT { get; set; }
        public Nullable<decimal> GIA { get; set; }
        private string _MOTA;
        public string MOTA { get => _MOTA; set { _MOTA = value; OnPropertyChanged(); } }
        public string HINHSP { get; set; }
        public Nullable<int> SL { get; set; }
        public string _LOAISP;
        public string LOAISP { get => _LOAISP; set { _LOAISP = value; OnPropertyChanged(); } }
        public string SIZE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPN> CTPNs { get; set; }
    }
}
